### ISSUE TITLE
Missing flush method in class RudderCleverTapIntegration causes a crash

### ISSUE THREAD

**Issue by nickbit** [rudderlabs/rudder-integration-clevertap-ios#20]
Missing `flush` method in class `RudderCleverTapIntegration` causes a crash.

This prevents us from using the library in a Pod.
A simple empty flush method will fix the crash.

![image](https://github.com/rudderlabs/rudder-integration-clevertap-ios/assets/179378/d01055a5-0f62-4a5c-8d4d-062c4c1a6417)

**Comment by desusai7** [comment]
Hey @nickbit 

Thank you for bringing this to our notice, we will check this

**Comment by 1abhishekpandey** [comment]
Hey @nickbit,
I apologize for the delayed response. It appears that you are using an older version of the `Rudder-CleverTap` SDK. Could you please specify the version you are currently using? I recommend upgrading to the latest version, which is [1.1.2](https://github.com/rudderlabs/rudder-integration-clevertap-ios/releases/tag/v1.1.2) which would fix the issue.

**Comment by 1abhishekpandey** [comment]
We are closing this issue. If you encounter any problems while using this integration, please feel free to reopen this issue or create a new one.
